Categorie:
    type: entity
    table: categorie
    id:
        idcategorie:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idCategorie
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        libelle:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
    lifecycleCallbacks: {  }
